export const sample_foods = [
  {
    id: '1',
    name: 'Pizza',
    cookTime: '10-20',
    price: 250,
    favorite: false,
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Masala Dosa',
    price: 100,
    cookTime: '20-30',
    favorite: true,
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'HamBurger',
    price: 50,
    cookTime: '10-15',
    favorite: false,
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Dal Fry',
    price: 350,
    cookTime: '15-20',
    favorite: true,
    stars: 3,
    imageUrl: 'food-4.jpg',
    tags: ['SlowFood', 'Fry'],
  },
  {
    id: '5',
    name: 'Chicken tikka',
    price: 400,
    cookTime: '40-50',
    favorite: false,
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'Manchow Soup',
    price: 110,
    cookTime: '40-50',
    favorite: false,
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 1 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];
